djangoproject.com/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'weblog'
urlpatterns = [
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\w-]+)/$',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    url(
        r'^(?P<year>\d{4})/$',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    url(
        r'^$',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

djangoproject.com/blog/models.py
from urllib.parse import urlparse

from django.conf import settings
from django.core.cache import caches
from django.db import models
from django.test import RequestFactory
from django.utils import timezone
from django.utils.cache import _generate_cache_header_key
from django.utils.translation import ugettext_lazy as _
from django_hosts.resolvers import reverse
from docutils.core import publish_parts

BLOG_DOCUTILS_SETTINGS = {
    'doctitle_xform': False,
    'initial_header_level': 3,
    'id_prefix': 's-',
    'raw_enabled': False,
    'file_insertion_enabled': False,
}
BLOG_DOCUTILS_SETTINGS.update(getattr(settings, 'BLOG_DOCUTILS_SETTINGS', {}))


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.active().filter(pub_date__lte=timezone.now())

    def active(self):
        return self.filter(is_active=True)


CONTENT_FORMAT_CHOICES = (
    ('reST', 'reStructuredText'),
    ('html', 'Raw HTML'),
)


class Entry(models.Model):
    headline = models.CharField(max_length=200)
    slug = models.SlugField(unique_for_date='pub_date')
    is_active = models.BooleanField(
        help_text=_(
            "Tick to make this entry live (see also the publication date). "
            "Note that administrators (like yourself) are allowed to preview "
            "inactive entries whereas the general public aren't."
        ),
        default=False,
    )
    pub_date = models.DateTimeField(
        verbose_name=_("Publication date"),
        help_text=_(
            "For an entry to be published, it must be active and its "
            "publication date must be in the past."
        ),
    )
    content_format = models.CharField(choices=CONTENT_FORMAT_CHOICES, max_length=50)
    summary = models.TextField()
    summary_html = models.TextField()
    body = models.TextField()
    body_html = models.TextField()
    author = models.CharField(max_length=100)

    objects = EntryQuerySet.as_manager()

    class Meta:
        db_table = 'blog_entries'
        verbose_name_plural = 'entries'
        ordering = ('-pub_date',)
        get_latest_by = 'pub_date'

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        kwargs = {
            'year': self.pub_date.year,
            'month': self.pub_date.strftime('%b').lower(),
            'day': self.pub_date.strftime('%d').lower(),
            'slug': self.slug,
        }
        return reverse('weblog:entry', kwargs=kwargs)

    def is_published(self):
        """
        Return True if the entry is publicly accessible.
        """
        return self.is_active and self.pub_date <= timezone.now()
    is_published.boolean = True

    def save(self, *args, **kwargs):
        if self.content_format == 'html':
            self.summary_html = self.summary
            self.body_html = self.body
        elif self.content_format == 'reST':
            self.summary_html = publish_parts(source=self.summary,
                                              writer_name="html",
                                              settings_overrides=BLOG_DOCUTILS_SETTINGS)['fragment']
            self.body_html = publish_parts(source=self.body,
                                           writer_name="html",
                                           settings_overrides=BLOG_DOCUTILS_SETTINGS)['fragment']
        super().save(*args, **kwargs)
        self.invalidate_cached_entry()

    def invalidate_cached_entry(self):
        url = urlparse(self.get_absolute_url())
        rf = RequestFactory(
            SERVER_NAME=url.netloc,
            HTTP_X_FORWARDED_PROTOCOL=url.scheme,
        )
        is_secure = url.scheme == 'https'
        request = rf.get(url.path, secure=is_secure)
        request.LANGUAGE_CODE = 'en'
        cache = caches[settings.CACHE_MIDDLEWARE_ALIAS]
        cache_key = _generate_cache_header_key(settings.CACHE_MIDDLEWARE_KEY_PREFIX, request)
        cache.delete(cache_key)


class EventQuerySet(EntryQuerySet):
    def past(self):
        return self.filter(date__lte=timezone.now()).order_by('-date')

    def future(self):
        return self.filter(date__gte=timezone.now()).order_by('date')


class Event(models.Model):
    headline = models.CharField(max_length=200, null=False)
    external_url = models.URLField()
    date = models.DateField()
    location = models.CharField(max_length=100)
    is_active = models.BooleanField(
        help_text=_(
            "Tick to make this event live (see also the publication date). "
            "Note that administrators (like yourself) are allowed to preview "
            "inactive events whereas the general public aren't."
        ),
        default=False,
    )
    pub_date = models.DateTimeField(
        verbose_name=_("Publication date"),
        help_text=_(
            "For an event to be published, it must be active and its "
            "publication date must be in the past."
        ),
    )

    objects = EventQuerySet.as_manager()

    class Meta:
        ordering = ('-pub_date',)
        get_latest_by = 'pub_date'

    def is_published(self):
        """
        Return True if the event is publicly accessible.
        """
        return self.is_active and self.pub_date <= timezone.now()
    is_published.boolean = True

djangoproject.com/blog/views.py
from django.views.generic.dates import (
    ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView,
    YearArchiveView,
)

from .models import Entry, Event


class BlogViewMixin:

    date_field = 'pub_date'
    paginate_by = 10

    def get_allow_future(self):
        return self.request.user.is_staff

    def get_queryset(self):
        if self.request.user.is_staff:
            return Entry.objects.all()
        else:
            return Entry.objects.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        events_queryset = Event.objects.future()
        if not self.request.user.is_staff:
            events_queryset = events_queryset.published()

        context['events'] = events_queryset[:3]

        return context


class BlogArchiveIndexView(BlogViewMixin, ArchiveIndexView):
    pass


class BlogYearArchiveView(BlogViewMixin, YearArchiveView):
    make_object_list = True


class BlogMonthArchiveView(BlogViewMixin, MonthArchiveView):
    pass


class BlogDayArchiveView(BlogViewMixin, DayArchiveView):
    pass


class BlogDateDetailView(BlogViewMixin, DateDetailView):
    pass

djangoproject.com/djangoproject/templates/blog/blog_pagination.html
{% if is_paginated %}
<div class="pagination">
  <ul class="nav-pagination" role="navigation">
    {% if page_obj.has_previous %}
    <li><a class="previous" href="?page={{ page_obj.previous_page_number }}">
      <i class="icon icon-chevron-left"></i>
      <span class="visuallyhidden">Previous</span>
    </a></li>
    {% endif %}
    <span class="page-current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj.has_next %}
    <li><a class="next" href="?page={{ page_obj.next_page_number }}">
      <i class="icon icon-chevron-right"></i>
      <span class="visuallyhidden">Next</span>
    </a></li>
    {% endif %}
  </ul>
</div>
{% endif %}

djangoproject.com/djangoproject/templates/blog/entry_archive.html
{% extends "base_weblog.html" %}

{% block content %}

  {% comment %}
    {# This is not implemented in backend yet #}
    <form action="#" class="form-input" role="search">
      <label class="visuallyhidden" for="news-search">Search:</label>
      <input type="text" name="news-search" id="news-search" placeholder="Search News" />
      <button type="submit">
        <i class="icon icon-search"></i>
        <span class="visuallyhidden">Search</span>
      </button>
    </form>
  {% endcomment %}

  <ul class="list-news">

  {% for object in latest %}
    {% include 'blog/news_summary.html' with object=object %}
  {% endfor %}

  </ul>

  {% include 'blog/blog_pagination.html' %}

{% endblock %}

djangoproject.com/djangoproject/templates/blog/entry_archive_day.html
{% extends "base_weblog.html" %}

{% block title %}{{ day|date:"F j" }} | Weblog{% endblock %}

{% block content %}

<h1>{{ day|date:"F j" }} archive</h1>

<ul class="list-news">

{% for object in object_list %}
  {% include 'blog/news_summary.html' with object=object %}
{% endfor %}

</ul>

{% include 'blog/blog_pagination.html' %}

{% endblock %}

djangoproject.com/djangoproject/templates/blog/entry_archive_month.html
{% extends "base_weblog.html" %}

{% block title %}{{ month|date:"F" }} | Weblog{% endblock %}

{% block content %}

<h1>{{ month|date:"F Y" }} archive</h1>

<ul class="list-news">

{% for object in object_list %}
  {% include 'blog/news_summary.html' with object=object %}
{% endfor %}

</ul>

{% include 'blog/blog_pagination.html' %}

{% endblock %}

djangoproject.com/djangoproject/templates/blog/entry_archive_year.html
{% extends "base_weblog.html" %}

{% block title %}{{ year|date:"Y" }} | Weblog{% endblock %}

{% block content %}

<h1>{{ year|date:"Y" }} archive</h1>

<ul class="list-news">

{% for object in object_list %}
  {% include 'blog/news_summary.html' with object=object %}
{% endfor %}

</ul>

{% include 'blog/blog_pagination.html' %}

{% endblock %}

djangoproject.com/djangoproject/templates/blog/entry_detail.html
{% extends "base_weblog.html" %}

{% block title %}{{ object.headline|escape }} | Weblog{% endblock %}

{% block content %}
<h2>{{ object.headline|safe }}</h2>

<span class="meta">Posted by <strong>{{ object.author }}</strong> on {{ object.pub_date|date:"F j, Y" }} {% comment %}in <a href="#">Release Announcements</a>{% endcomment %}</span>

{{ object.body_html|safe }}
{% endblock %}

djangoproject.com/djangoproject/templates/blog/entry_snippet.html
<ul class="list-news">
{% for e in entries %}
    {% include 'blog/news_summary.html' with object=e %}
{% endfor %}
</ul>

djangoproject.com/djangoproject/templates/blog/month_links_snippet.html
  {% load i18n %}
  {% regroup dates by year as dates_by_year %}

  <ul class="list-collapsing active">
  {% for month in dates_by_year %}
    <li id="year{{ month.grouper }}"{% if forloop.first %} class="active"{% endif %}>
      <h2><a href="{% url 'weblog:archive-year' month.grouper %}">{{ month.grouper }}</a> <i class="collapsing-icon icon icon-plus"></i></h2>
      <div class="collapsing-content">
        <ul class="list-links-small">
          {% for d in month.list %}
            <li><a href="{% language "en" %}{% url 'weblog:archive-month' d|date:"Y" d|date:"b" %}{% endlanguage %}">{{ d|date:"F Y" }}</a></li>
          {% endfor %}
        </ul>
        <p></p>
      </div>
    </li>
  {% endfor %}
  </ul>

djangoproject.com/djangoproject/templates/blog/news_summary.html
<li{% if not object.is_published %} class="unpublished"{% endif %}>
  <{{ header_tag|default:'h2' }}>
    <a href="{{ object.get_absolute_url }}">{{ object.headline|safe }}</a>
  </{{ header_tag|default:'h2' }}>
  {% if summary_first %}
    {{ object.summary_html|safe }}
  {% endif %}
  <span class="meta">
    Posted by <strong>{{ object.author }}</strong> on {{ object.pub_date|date:"F j, Y" }}
  </span>
  {% if not summary_first %}
    {{ object.summary_html|safe }}
  {% endif %}
  {% if not hide_readmore %}
  <a class="link-readmore" href="{{ object.get_absolute_url }}">Read more</a>
  {% endif %}
</li>