djangoproject.com/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'weblog'
urlpatterns = [
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\w-]+)/$',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    url(
        r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    url(
        r'^(?P<year>\d{4})/$',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    url(
        r'^$',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

djangoproject.com/fundraising/urls.py
from django.conf.urls import url

from . import views

app_name = 'fundraising'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^thank-you/(?P<donation>[\w]+)/$', views.thank_you, name='thank-you'),
    url(r'^manage-donations/(?P<hero>[\w]+)/$', views.manage_donations, name='manage-donations'),
    url(r'^manage-donations/(?P<hero>[\w]+)/cancel/$', views.cancel_donation, name='cancel-donation'),
    url(r'^receive-webhook/$', views.receive_webhook, name='receive-webhook'),
    url(r'^update-card/$', views.update_card, name='update-card'),
]

djangoproject.com/fundraising/models.py
import datetime
from decimal import Decimal

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import crypto, timezone
from django_hosts.resolvers import reverse
from sorl.thumbnail import ImageField, get_thumbnail

GOAL_AMOUNT = Decimal("200000.00")
GOAL_START_DATE = datetime.date(2018, 1, 1)
DISPLAY_DONOR_DAYS = 365
DEFAULT_DONATION_AMOUNT = 50
LEADERSHIP_LEVEL_AMOUNT = Decimal("1000.00")
INTERVAL_CHOICES = (
    ('monthly', 'Monthly donation'),
    ('quarterly', 'Quarterly donation'),
    ('yearly', 'Yearly donation'),
    ('onetime', 'One-time donation'),
)


class DjangoHeroManager(models.Manager):
    def for_public_display(self):
        donors = self.get_queryset().filter(
            is_visible=True,
            approved=True,
            donation__payment__date__gt=datetime.date.today() - datetime.timedelta(days=DISPLAY_DONOR_DAYS),
        ).annotate(donated_amount=models.Sum('donation__payment__amount'))
        return donors.order_by('-donated_amount', 'name')


class FundraisingModel(models.Model):
    id = models.CharField(max_length=12, primary_key=True)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.modified = timezone.now()
        if not self.id:
            self.id = crypto.get_random_string(length=12)
        return super().save(*args, **kwargs)


class DjangoHero(FundraisingModel):
    email = models.EmailField(blank=True)
    stripe_customer_id = models.CharField(max_length=100, blank=True)
    logo = ImageField(upload_to="fundraising/logos/", blank=True)
    url = models.URLField(blank=True, verbose_name='URL')
    name = models.CharField(max_length=100, blank=True)
    location = models.CharField(max_length=255, blank=True)
    HERO_TYPE_CHOICES = (
        ('individual', 'Individual'),
        ('organization', 'Organization'),
    )
    hero_type = models.CharField(max_length=30, choices=HERO_TYPE_CHOICES, blank=True)
    is_visible = models.BooleanField(
        default=False,
        verbose_name="Agreed to displaying on the fundraising page?",
    )
    is_subscribed = models.BooleanField(
        default=False,
        verbose_name="Agreed to being contacted by DSF?",
    )
    approved = models.NullBooleanField(
        verbose_name="Name, URL, and Logo approved?",
    )

    objects = DjangoHeroManager()

    def __str__(self):
        return self.name if self.name else 'Anonymous #{}'.format(self.pk)

    class Meta:
        verbose_name = "Django hero"
        verbose_name_plural = "Django heroes"

    @property
    def display_name(self):
        return self.name

    @property
    def thumbnail(self):
        return get_thumbnail(self.logo, '170x170', quality=100)

    @property
    def name_with_fallback(self):
        return self.name if self.name else 'Anonymous Hero'


class Donation(FundraisingModel):
    interval = models.CharField(max_length=20, choices=INTERVAL_CHOICES, blank=True)
    subscription_amount = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    donor = models.ForeignKey(DjangoHero, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=100, blank=True)
    stripe_customer_id = models.CharField(max_length=100, blank=True)
    receipt_email = models.EmailField(blank=True)

    def __str__(self):
        return '{} from {}'.format(self.get_interval_display(), self.donor)

    def get_absolute_url(self):
        return reverse('fundraising:thank-you', kwargs={'donation': self.id})

    def is_active(self):
        return bool(self.stripe_subscription_id)
    is_active.boolean = True

    def total_payments(self):
        return self.payment_set.aggregate(models.Sum('amount'))['amount__sum']


class Payment(models.Model):
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2, null=True)
    stripe_charge_id = models.CharField(max_length=100, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '${}'.format(self.amount)


class Testimonial(models.Model):
    author = models.CharField(max_length=255)
    body = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.author


class InKindDonor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(blank=True, verbose_name='URL')
    description = models.TextField()
    logo = ImageField(upload_to='fundraising/logos/', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'in-kind hero'
        verbose_name_plural = 'in-kind heroes'

    @property
    def display_name(self):
        return self.name

    @property
    def thumbnail(self):
        return get_thumbnail(self.logo, '170x170', quality=100)


@receiver(post_save, sender=DjangoHero)
@receiver(post_save, sender=InKindDonor)
def create_thumbnail_on_save(sender, **kwargs):
    return kwargs['instance'].thumbnail

djangoproject.com/fundraising/views.py
import decimal
import json

import stripe
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.forms.models import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .exceptions import DonationError
from .forms import DjangoHeroForm, DonationForm, PaymentForm
from .models import (
    LEADERSHIP_LEVEL_AMOUNT, DjangoHero, Donation, Payment, Testimonial,
)


def index(request):
    testimonial = Testimonial.objects.filter(is_active=True).order_by('?').first()
    return render(request, 'fundraising/index.html', {
        'testimonial': testimonial,
    })


@require_POST
def donate(request):
    form = PaymentForm(request.POST)

    if form.is_valid():
        # Try to create the charge on Stripe's servers - this will charge the user's card
        try:
            donation = form.make_donation()
        except DonationError as donation_error:
            data = {
                'success': False,
                'error': str(donation_error),
            }
        else:
            data = {
                'success': True,
                'redirect': donation.get_absolute_url(),
            }
    else:
        data = {
            'success': False,
            'error': form.errors.as_json(),
        }
    return JsonResponse(data)


def thank_you(request, donation):
    donation = get_object_or_404(Donation, pk=donation)
    if request.method == 'POST':
        form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=donation.donor,
        )

        if form.is_valid():
            form.save()
            messages.success(request, "Thank you! You're a Hero.")
            return redirect('fundraising:index')
    else:
        form = DjangoHeroForm(instance=donation.donor)

    return render(request, 'fundraising/thank-you.html', {
        'donation': donation,
        'form': form,
        'leadership_level_amount': LEADERSHIP_LEVEL_AMOUNT,
    })


@never_cache
def manage_donations(request, hero):
    hero = get_object_or_404(DjangoHero, pk=hero)
    recurring_donations = hero.donation_set.exclude(stripe_subscription_id='')
    past_payments = Payment.objects.filter(donation__donor=hero).select_related('donation')

    ModifyDonationsFormset = modelformset_factory(Donation, form=DonationForm, extra=0)

    if request.method == 'POST':
        hero_form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=hero,
        )
        modify_donations_formset = ModifyDonationsFormset(
            request.POST,
            queryset=recurring_donations
        )

        if hero_form.is_valid() and modify_donations_formset.is_valid():
            hero_form.save()
            modify_donations_formset.save()
            messages.success(request, "Your information has been updated.")
    else:
        hero_form = DjangoHeroForm(instance=hero)
        modify_donations_formset = ModifyDonationsFormset(
            queryset=recurring_donations
        )

    return render(request, 'fundraising/manage-donations.html', {
        'hero': hero,
        'hero_form': hero_form,
        'modify_donations_formset': modify_donations_formset,
        'recurring_donations': recurring_donations,
        'past_payments': past_payments,
        'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY,
    })


@require_POST
def update_card(request):
    donation = get_object_or_404(Donation, id=request.POST['donation_id'])
    try:
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        subscription.source = request.POST['stripe_token']
        subscription.save()
    except stripe.StripeError as e:
        data = {'success': False, 'error': str(e)}
    else:
        data = {'success': True}
    return JsonResponse(data)


@require_POST
def cancel_donation(request, hero):
    donation_id = request.POST.get('donation')
    hero = get_object_or_404(DjangoHero, pk=hero)
    donations = hero.donation_set.exclude(stripe_subscription_id='')
    donation = get_object_or_404(donations, pk=donation_id)

    customer = stripe.Customer.retrieve(donation.stripe_customer_id)
    customer.subscriptions.retrieve(donation.stripe_subscription_id).delete()

    donation.stripe_subscription_id = ''
    donation.save()

    messages.success(request, "Your donation has been canceled.")
    return redirect('fundraising:manage-donations', hero=hero.pk)


@require_POST
@csrf_exempt
def receive_webhook(request):
    try:
        data = json.loads(request.body.decode())
    except ValueError:
        return HttpResponse(422)

    # For security, re-request the event object from Stripe.
    try:
        event = stripe.Event.retrieve(data['id'])
    except stripe.error.InvalidRequestError:
        return HttpResponse(422)

    return WebhookHandler(event).handle()


class WebhookHandler:
    def __init__(self, event):
        self.event = event

    def handle(self):
        handlers = {
            'invoice.payment_succeeded': self.payment_succeeded,
            'invoice.payment_failed': self.payment_failed,
            'customer.subscription.deleted': self.subscription_cancelled,
        }
        handler = handlers.get(self.event.type, lambda: HttpResponse(422))
        return handler()

    def payment_succeeded(self):
        invoice = self.event.data.object
        # Ensure we haven't already processed this payment
        if Payment.objects.filter(stripe_charge_id=invoice.charge).exists():
            # We need a 2xx response otherwise Stripe will keep trying.
            return HttpResponse()
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)
        amount = decimal.Decimal(invoice.total) / 100
        if invoice.charge:
            donation.payment_set.create(amount=amount, stripe_charge_id=invoice.charge)
        return HttpResponse(status=201)

    def subscription_cancelled(self):
        subscription = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=subscription.id)
        donation.stripe_subscription_id = ''
        donation.save()

        mail_text = render_to_string(
            'fundraising/email/subscription_cancelled.txt', {'donation': donation})
        send_mail('Payment cancelled', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def payment_failed(self):
        invoice = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)

        mail_text = render_to_string(
            'fundraising/email/payment_failed.txt', {'donation': donation})
        send_mail('Payment failed', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

djangoproject.com/djangoproject/templates/fundraising/index.html
{% extends 'base.html' %}
{% load fundraising_extras humanize static %}

{% block title %}Support Django{% endblock %}
{% block layout_class %}full-width{% endblock %}

{% block header %}
<h1 class="visuallyhidden">Support Django</h1>
<p><em>Support Django development</em> by donating to the <em>Django Software Foundation</em>.</p>
{% endblock %}

{% block messages %}

  {% if messages %}
    {% for message in messages %}
    <h1>{{ message }}</h1>
    {% endfor %}
    <hr>
  {% endif %}

{% endblock %}

{% block content %}

<h1>Support the Django Software Foundation!</h1>

{% donation_form_with_heart %}

<h2 id="why-give">Why give to the Django Software Foundation?</h2>

<p>Our main focus is direct support of Django's developers. This means:</p>
<ul>
<li>Organizing and funding development sprints so that Django's developers can
meet in person.</li>
<li>Helping key developers attend these sprints and other community events by
covering travel expenses to official Django events.</li>
<li>Providing financial assistance to community development and outreach
projects such as <a href="#django-girls">Django Girls</a>.</li>
<li>Providing financial assistance to individuals so they can attend major
conferences and events.</li>
<li>Funding the <a href="#fellowship-program">Django Fellowship program</a>,
which provides full-time staff to perform community management tasks in the
Django community.</li>
</ul>

<p>Still curious? See our <a href="/foundation/donate/">Frequently Asked Questions</a>
about donations.</p>

<h2 id="fellowship-program">Django Fellowship Program</h2>

<p>The biggest expense of the <abbr title="Django Software Foundation">DSF</abbr>
  is the Django Fellowship program. It's a project where
  <a href="#who-is-the-django-fellow">a paid contractor</a> is engaged to
  manage some of the administrative and community management tasks of the
  Django project to support rapid development of Django itself.</p>

<p><strong>The Django Fellowship program has a major positive impact on how
  Django is developed and maintained.</strong>
  The Django Fellow triages 10-15 new tickets each week and reviews and merges
  around fifteen non-trivial patches a week from the community. Release
  blocking and severe bugs aren't postponed indefinitely. Major releases happen
  according to an 8 month schedule and bug fix releases occur monthly.</p>

<p>For more details, you can read retrospectives for the
  <a href="/weblog/2015/jan/21/django-fellowship-retrospective/"> first three
  months of the program</a>,
  <a href="/weblog/2015/dec/17/fellowship-2015-retrospective/">2015</a>, and
  <a href="/weblog/2016/dec/28/fellowship-2016-retrospective/">2016</a>.
</p>

<p>The Django Fellow is a resource to help review patches and contributions
   from the community, and the community loves that:</p>

   {% if testimonial %}
   <blockquote>
     {{ testimonial.body|linebreaks }}
     <em>{{ testimonial.author }}</em>
   </blockquote>
   {% endif %}

<p><strong>If you use Django on a daily basis and care about the development of Django
   itself, you should donate today</strong> (may be <a href="/foundation/donate/#tax-deductible">tax deductible</a>).
   Only with your support can we make sure that the Web framework you base your work on
   can grow to be even better in the coming years.</p>

<h2 id="django-girls">Django Girls Outreach</h2>

<p>Supporting <a href="https://djangogirls.org/">Django Girls workshops</a> is
a significant priority for the Django Software Foundation. Django Girls
workshops are organized by volunteers and are provided as free events for women
who want to learn to code. The workshop serves as an introduction to Python and
Django, where attendees learn usable skills to build their first web app.</p>

<p>Django Girls workshop attendees go on to organize their own workshops, lead
in their community, and secure full-time jobs as developers. Read their stories
in the “Your Django Story” series on the <a href="http://blog.djangogirls.org/">
Django Girls blog</a>.</p>

<p>In 2015, the Django Software Foundation contributed $5,400 to eighteen
Django Girls workshops around the world. Here's what some of the organizers had
to say about the impact:</p>

<blockquote>
<p>Sponsorship from the DSF allowed us to have on-site child care for our Django
Girls Portland workshop. We hosted 2 young children and an infant, and provided
them with healthy snacks, games, sidewalk chalk, finger paint, and emoji
stickers. Without our nanny, 3 of our attendees wouldn't have been able to come
to the workshop. Finger paint photo is
<a href="http://blog.djangogirls.org/post/124680859493/django-girls-portland-a-retrospective">
on the blog</a>!</p>
<em>Lacey - Portland, Oregon, US</em>
</blockquote>

<blockquote>
<p>The DSF supported <a href="https://djangogirls.org/warsaw/">Django Girls
Poland</a> four times this year and the impact was enormous! In Poland, diversity
awareness is not a very common topic. When we approached different local
companies about our workshops they usually didn't get what we were actually
doing and why it is important. If not for the DSF, we probably would not have
been able to hold our workshops at all. Our first workshops were the only until
now workshops that were 100% female - female only coaches and female only
attendees. Thanks to you, we were able to focus on gathering female mentors
instead of searching for sponsors!</p>
<em>Ania - Wrocław, Poland</em>
</blockquote>

<blockquote>
<p><a href="https://pyfound.blogspot.kr/2015/10/django-girls-seoul-great-success.html">
Django Girls Seoul</a> had 425 applicants from 11 different countries ages
ranging from 16 to 50 years old. After acceptances, we had about 105 people to
feed and caffeinate! Thanks to Django's sponsorship we could get all of our
participants coffee for the day. It really made a huge difference because we
all know how a cup of coffee can change the atmosphere and mood! We were so
grateful to the sponsorship we received from abroad. We tried to get sponsorship
from a lot of Korean companies but the same generosity doesn't translate well
into a Korean Business culture, I guess. This made us even more thankful for
our friends at the DSF!</p>
<em>Rachell - Seoul, South Korea</em>
</blockquote>

<h1>Other ways to give</h1>
<ul>
  <li><a href="/foundation/donate/#benevity-giving">Benevity Workplace Giving
    Program</a> - If your employer participates, you can make donations to the
    DSF via payroll deduction.</li>
  <li><a href="/foundation/donate/#amazon-smile">Amazon Smile</a> - When you
    shop at Amazon, you can nominate for 0.5% of the purchase price of your
    eligible purchases to be donated to the DSF.</li>
</ul>

<hr style="margin: 40px 0" />

<div class="heroes-section">
  <h1>DSF Supporters</h1>
  <p>Our donors make our work possible! We are incredibly grateful for the
  financial support from the following individuals and organizations in our
  community.</p>

  {% display_django_heroes %}
</div>
{% endblock %}

{% block content-extra %}
  <div class="layout-tertiary" id="about">
    <div class="container">
      <h2>What is the Django Software Foundation?</h2>
      <p>Development of Django is supported by an independent foundation
        established as a 501(c)(3) non-profit. Like most open-source foundations,
        the goal of the <a href="/foundation/">Django Software Foundation</a>
        is to promote, support, and advance the Django Web framework. If you're
        interested in how the Django Software Foundation supports the Django
        Web framework, we published a
        <a href="/weblog/2015/jan/08/django-software-foundation-2014/">Summary
          of 2014. </a>
      </p>

      <h2 id="who-is-the-django-fellow">Who is the Django Fellow?</h2>
      <p><strong>Tim Graham</strong> - a member of the core team for several years. For
        the 12 months before the fellowship began, he was a major contributor,
        reviewing and merging pull requests. Tim was contracted as a full-time
        Fellow for the duration of the 3 month pilot and continued when the
        program was renewed in March 2015.</p>
    </div>
  </div>
{% endblock %}

djangoproject.com/djangoproject/templates/fundraising/manage-donations.html
{% extends 'fundraising/index.html' %}
{% load staticfiles %}

{% block messages %}

  {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    <hr>
  {% endif %}

{% endblock %}

{% block content %}

<h1>Manage your donations to the Django Software Foundation</h1>
<p>Your support is <strong>invaluable</strong> to continue the rapid development
  of Django and helps the <strong>Django Fellowship</strong> program in particular.
  Thank you!</p>

<form enctype="multipart/form-data" action="" method="post" class="form-input django-hero-form"
    data-stripe-key="{{ stripe_publishable_key }}" data-stripe-icon="{% static 'img/dj-stripe-icon.jpg' %}"
    data-update-card-url="{% url 'fundraising:update-card' %}">
  <h2>Manage your participation in the fundraising campaigns</h2>
  <p>Information entered below will be visible on all of your donations to the Django Project.</p>
  {% csrf_token %}
  {% include 'fundraising/includes/_form.html' with form=hero_form %}
  <p class="submit">
    <input type="submit" class="cta" value="Save &rarr;">
  </p>
  {# Always include to avoid "Management form has been tampered with" if no recurring donations exist #}
  {{ modify_donations_formset.management_form }}
  {% if recurring_donations %}
    <hr />
    <h2>Modify your recurring donations</h2>
    <p>Update the time interval or amount of your recurring donation here:</p>
    {% for form in modify_donations_formset %}
      {% include 'fundraising/includes/_form.html' %}
      <div class="change-card-container">
        <input type="button" value="Change card details" class="change-card cta outline inline"
            data-donation-id="{{ form.instance.id }}" data-donor-email="{{ hero.email }}">
        <span class="change-card-result"></span>
      </div>
    {% endfor %}
    <p class="submit">
      <input type="submit" class="cta" value="Save &rarr;">
    </p>
</form>
    <hr />
    <h2>Cancel your recurring donations</h2>
    <p>You can cancel your recurring donation to the Django Software Foundation anytime.</p>
    <ul>
    {% for donation in recurring_donations %}
      <li>
        Your {{ donation.interval }} recurring donation of ${{ donation.subscription_amount }}.
        <form method="POST" action="{% url 'fundraising:cancel-donation' hero.pk %}">
          {% csrf_token %}
          <input name="donation" type="hidden" value="{{ donation.pk }}">
          <input type="submit" value="cancel this donation">
        </form>
      </li>
    {% endfor %}
    </ul>
  {% else %}
</form>
  {% endif %}
  {% if past_payments %}
  <hr />
    <h2>Your past donations</h2>
    <ul>
    {% for payment in past_payments %}
      <li>
        ${{ payment.amount }} on {{ payment.date|date:"N jS, Y \a\t P" }}
        ({{ payment.donation.get_interval_display }})
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

{% block content-extra %}{% endblock %}

djangoproject.com/djangoproject/templates/fundraising/thank-you.html
{% extends 'fundraising/index.html' %}
{% load humanize static %}

{% block content %}
<h1>Thank you for supporting the Django Project!</h1>
<p>Your support is <strong>invaluable</strong> to continue the rapid development
  of Django and helps the <strong>Django Fellowship</strong> program in particular.</p>

<p>Please help us spread the word and encourage your friends and colleagues to
  donate. Thank you!</p>

<a href="https://twitter.com/intent/tweet?button_hashtag=SupportDjango&text=I+just+donated+to+support+the+Django+Software+Foundation.+Join+me!+https%3A%2F%2Fwww.djangoproject.com%2Ffundraising%2F"
  class="twitter-hashtag-button" data-related="djangoproject">Tweet #SupportDjango</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

<p>We'd love if you proudly displayed a badge on your website or online profile
to help spread the word about our campaign. You may use the "Leader" badge if
you donated more than ${{ leadership_level_amount|intcomma }} per year.</p>

<p>
  <a href="https://www.djangoproject.com/fundraising/">
    <img width="80" height="65" border="0" title="Django Hero" alt="Django Hero"
      src="{% static "img/badges/django-hero.png" %}"></a>
&nbsp; &nbsp;
  <a href="https://www.djangoproject.com/fundraising/">
    <img src="{% static "img/badges/dsf-leader.png" %}"
      width="126" height="70" border="0" title="Django Leader" alt="Django Leader"></a>
</p>

<p>If you'd like to have your name or company displayed on the
  <a href="{% url 'fundraising:index' %}">Fundraising page</a> and in the sidebar
  on the Django Project website, please fill out the form below. This is, of
  course, <em>optional</em>.
</p>

<form enctype="multipart/form-data" action="" method="post" class="form-input django-hero-form">
  <h2>You're now a Django Hero</h2>
  Enter your details below to show up on our <a href="{% url "fundraising:index" %}">fundraising page</a>.
  {% csrf_token %}
  {% include 'fundraising/includes/_form.html' %}
  <p class="submit">
    <input type="submit" class="cta" value="Save &rarr;">
  </p>
</form>

{% endblock %}

{% block content-extra %}{% endblock %}